---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  users:
    post:
      summary: Creates a user
      tags:
      - Users
      consumes:
      - application/json
      - application/xml
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            first_name:
              type: string
          required:
          - name
          - email
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
  users/{id}:
    get:
      summary: Retrieves a user
      tags:
      - Users
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: name found
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              email:
                type: string
              first_name:
                type: string
            required:
            - id
            - name
            - email
        '404':
          description: pet not found
